services:
  - type: web
    name: laravel-backend
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    autoDeploy: true

databases:
  - name: ordercontrol-db
    databaseName: OrderControl
    user: postgres
